# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SampleFirebase2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleFirebase2

  pod 'Firebase'
  pod 'Firebase/Database'


end
